sched: Re-Introduce BORE CPU Scheduler (4.2.0)
BORE (Burst-Oriented Response Enhancer) CPU Scheduler 4.2.0

taken from https://github.com/firelzrd/bore-scheduler/tree/main/patches/linux-4.19-bore
--
fix and adapt issues accordingly
-
../kernel/sched/fair.c:5662:13: error: ‘task_sleep’ undeclared (first use in this function); did you mean ‘task_new’?
 5662 |         if (task_sleep) {
      |             ^~~~~~~~~~
      |             task_new

--> add
int task_sleep = flags & DEQUEUE_SLEEP;

---
../kernel/sysctl.c:192:13: error: conflicting types for ‘three’; have ‘uint’ {aka ‘unsigned int’}
  192 | static uint three          = 3;
      |             ^~~~~
--> just gourd the first three defined
static int __maybe_unused three = 3;

taken from https://github.com/firelzrd/bore-scheduler/tree/main/patches/linux-4.19-bore

0001-linux4.19.y-bore4.2.0.patch
0002-constgran-vanilla-max.patch