Revert "fix errror ../techpack/display/msm/dsi/dsi_panel.c:536:2: error: use of undeclared identifier 'refresh_rate'"
This reverts commit 8f59cb956fce46be2174e09e0cf1e0baf4c5eeb1.