Revert "fix error ../techpack/display/msm/sde/sde_encoder.c:5070:21: error: no member named 'dsi_refresh_flag' in 'struct dsi_panel'"
This reverts commit fb7ba778c8c9100ee227c028253f5511c68fb958.